"""open_monitor 环境广播常量。"""

ENV_RUN_PREOPEN = "ENV_PREOPEN"
ENV_RUN_BREAK = "ENV_BREAK"
ENV_RUN_POSTCLOSE = "ENV_POSTCLOSE"

ENV_RUN_IDS = {
    ENV_RUN_PREOPEN,
    ENV_RUN_BREAK,
    ENV_RUN_POSTCLOSE,
}
